apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manictime
  namespace: manictime
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: traefik
  rules:
    - host: manic.datlycan.cc
      http:
        paths:
          - backend:
              service:
                name: manictime-router
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - manic.datlycan.cc
