# --- Persistent Volume Claim ---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-manictime
  namespace: manictime
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30Gi
  storageClassName: nas-retain
